# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '03-tableview-ui' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # *********************************************** Swift ***********************************************

	pod 'SwiftyJSON'
	pod 'SnapKit'
  pod 'ReachabilitySwift'
  pod 'SwiftDate'

  # *********************************************** Objective-C ***********************************************
	pod 'MBProgressHUD'
	pod 'MJRefresh'
 	pod 'YYText'
     
end



post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end


install! 'cocoapods',
          disable_input_output_paths: true,
          generate_multiple_pod_projects: true
